(() => {
  const tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;
  const SUPABASE_URL='https://uqgckzrmibdgxkxdfzav.supabase.co';
  const SUPABASE_KEY='sb_publishable_KBodwmECQvN46zDKjOwfhg_fet6nBiy';
  const headers={apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY};
  let currentShop=null,menuItems=[],cart=[],favorites=[],currentCat='Barchasi',submitting=false;
  const shopCode=getShopCode();
  try{
    tg&&tg.ready();tg&&tg.expand();tg&&tg.disableVerticalSwipes&&tg.disableVerticalSwipes();tg&&tg.setHeaderColor&&tg.setHeaderColor('#f5f7fb');tg&&tg.setBackgroundColor&&tg.setBackgroundColor('#f5f7fb');
    const user=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;
    if(user){const initials=((user.first_name||'U')[0]+(user.last_name||'')[0]).toUpperCase();document.getElementById('userAvatar').textContent=initials;document.getElementById('heroTitle').textContent='Salom, '+(user.first_name||'mehmon')+'!';}
  }catch(_){}
  function getShopCode(){const params=new URLSearchParams(location.search);const raw=(tg&&tg.initDataUnsafe&&tg.initDataUnsafe.start_param)||params.get('shop')||params.get('startapp')||params.get('start_param')||'B001';return String(raw).trim().toUpperCase();}
  function money(value){return Number(value||0).toLocaleString('uz-UZ')+' so‘m';}
  function escapeHtml(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function imageUrl(value){const url=String(value||'');return /^https?:\/\//i.test(url)?url:'';}
  function key(name){return 'bozorfood_'+name+'_'+shopCode;}
  function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(function(){el.classList.remove('show');},2600);}
  function haptic(type){try{tg&&tg.HapticFeedback&&tg.HapticFeedback.impactOccurred(type||'light');}catch(_){}}
  async function json(url){const response=await fetch(url,{headers:headers});const raw=await response.text();let data=[];try{data=raw?JSON.parse(raw):[];}catch(_){}if(!response.ok)throw new Error(data.message||data.error||'Server xatosi');return data;}
  function loadLocal(){try{cart=JSON.parse(localStorage.getItem(key('cart'))||'[]');}catch(_){cart=[];}try{favorites=JSON.parse(localStorage.getItem('favorites')||'[]');}catch(_){favorites=[];}}
  function saveLocal(){localStorage.setItem(key('cart'),JSON.stringify(cart));localStorage.setItem('favorites',JSON.stringify(favorites));}
  async function loadShop(){const data=await json(SUPABASE_URL+'/rest/v1/shops?shop_code=eq.'+encodeURIComponent(shopCode)+'&is_active=eq.true&select=*');if(!data.length)throw new Error(shopCode+' do‘koni topilmadi');currentShop=data[0];document.getElementById('shopName').textContent=currentShop.display_name||currentShop.market_name||'Do‘kon';document.getElementById('shopLocation').textContent=currentShop.address||[currentShop.market_name,currentShop.row_name,currentShop.shop_number?'Do‘kon '+currentShop.shop_number:''].filter(Boolean).join(', ')||'Manzil ko‘rsatilmagan';document.getElementById('shopId').textContent=currentShop.shop_code||shopCode;}
  async function loadMenu(){menuItems=await json(SUPABASE_URL+'/rest/v1/menu_items?shop_code=eq.'+encodeURIComponent(shopCode)+'&is_available=eq.true&select=*&order=id.asc');renderCategories();renderMenu();}
  function renderCategories(){const el=document.getElementById('categories');const categories=['Barchasi'].concat(Array.from(new Set(menuItems.map(function(x){return x.category;}).filter(Boolean))));el.innerHTML=categories.map(function(c){return '<button class="cat '+(c===currentCat?'active':'')+'" data-category="'+escapeHtml(c)+'">'+escapeHtml(c)+'</button>';}).join('');el.onclick=function(event){const button=event.target.closest('[data-category]');if(!button)return;currentCat=button.getAttribute('data-category');renderCategories();renderMenu();haptic('light');};}
  function renderMenu(){const search=document.getElementById('searchInput').value.toLowerCase().trim();const filtered=menuItems.filter(function(item){return (currentCat==='Barchasi'||item.category===currentCat)&&(String(item.name||'')+' '+String(item.category||'')).toLowerCase().indexOf(search)!==-1;});document.getElementById('menuMeta').textContent=filtered.length+' ta taom';if(!filtered.length){document.getElementById('menu').innerHTML='<div class="empty"><div class="empty-icon">🍽️</div><strong>Taom topilmadi</strong><span>Boshqa nom yoki kategoriya bilan izlab ko‘ring.</span></div>';return;}document.getElementById('menu').innerHTML=filtered.map(function(item,index){const row=cart.find(function(x){return Number(x.id)===Number(item.id);});const qty=row?row.qty:0;const stock=Math.max(Number(item.stock||0),0);const image=imageUrl(item.image_url);const fav=favorites.includes(Number(item.id));return '<article class="item '+(stock===0?'sold-out':'')+'" style="animation-delay:'+(index*25)+'ms"><div class="item-media">'+(image?'<img src="'+escapeHtml(image)+'" alt="'+escapeHtml(item.name)+'">':'🍽️')+'</div><div class="info"><h3>'+escapeHtml(item.name||'Taom')+'</h3><p>'+escapeHtml(item.category||'Mazali taom')+'</p><div class="price">'+money(item.price)+'</div><small class="stock">'+(stock?'Qoldiq: '+stock+' dona':'Hozircha tugagan')+'</small></div><div class="item-actions"><button class="favorite '+(fav?'active':'')+'" data-favorite="'+item.id+'" aria-label="Sevimliga qo‘shish">'+(fav?'♥':'♡')+'</button><button class="add '+(qty?'has-qty':'')+'" data-add="'+item.id+'" '+(stock===0||qty>=stock?'disabled':'')+'>'+(qty||'+')+'</button></div></article>';}).join('');}
  function totals(){return cart.reduce(function(a,x){a.count+=x.qty;a.total+=x.qty*Number(x.price||0);return a;},{count:0,total:0});}
  function updateCart(){const result=totals();document.getElementById('cartCount').textContent=result.count;document.getElementById('cartTotal').textContent=money(result.total);document.getElementById('checkoutTotal').textContent=money(result.total);document.getElementById('cartButton').classList.toggle('hidden',result.count===0);document.getElementById('cartItems').innerHTML=cart.length?cart.map(function(x){return '<div class="cart-row"><div><strong>'+escapeHtml(x.name)+'</strong><small>'+money(x.price)+'</small></div><div class="qty"><button data-change="'+x.id+'" data-delta="-1">−</button><strong>'+x.qty+'</strong><button data-change="'+x.id+'" data-delta="1">+</button></div></div>';}).join(''):'<div class="empty">Savatcha hozircha bo‘sh.</div>';}
  function addToCart(id){const item=menuItems.find(function(x){return Number(x.id)===Number(id);});if(!item)return;const row=cart.find(function(x){return Number(x.id)===Number(id);});const qty=row?row.qty:0;if(qty>=Number(item.stock||0)){toast('Bu mahsulotning qoldig‘i yetarli emas.');return;}if(row)row.qty++;else cart.push({id:item.id,name:item.name,price:Number(item.price),stock:Number(item.stock||0),qty:1});saveLocal();updateCart();renderMenu();haptic('light');}
  function changeQty(id,delta){const row=cart.find(function(x){return Number(x.id)===Number(id);});if(!row)return;if(delta>0&&row.qty>=Number(row.stock||0)){toast('Qoldiq tugadi.');return;}row.qty+=delta;if(row.qty<=0)cart=cart.filter(function(x){return Number(x.id)!==Number(id);});saveLocal();updateCart();renderMenu();haptic('light');}
  function modal(id,open){document.getElementById(id).classList.toggle('hidden',!open);}
  async function submitOrder(){if(submitting)return;if(!cart.length){toast('Savatcha bo‘sh.');return;}if(!navigator.onLine){toast('Internet ulanishini tekshiring.');return;}const phone=document.getElementById('phone').value.trim();if(phone.replace(/\D/g,'').length<7){toast('Telefon raqamingizni to‘liq kiriting.');document.getElementById('phone').focus();return;}if(!currentShop){toast('Do‘kon ma’lumotlari hali tayyor emas.');return;}const user=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;const payload={shop_code:currentShop.shop_code,customer_name:user?(user.first_name||''):'',phone:phone,delivery_address:currentShop.address||[currentShop.market_name,currentShop.row_name,currentShop.shop_number?'Do‘kon '+currentShop.shop_number:''].filter(Boolean).join(', '),items:cart.map(function(x){return {id:x.id,quantity:x.qty};}),total:totals().total,note:document.getElementById('note').value.trim()};submitting=true;const button=document.getElementById('orderButton');button.disabled=true;button.textContent='Yuborilmoqda...';try{const result=await window.RastaGoOrderApi.createOrder(payload,window.RastaGoOrderApi.uuid());document.getElementById('orderNumber').textContent='Buyurtma № '+(result.order_number||'qabul qilindi');modal('cartModal',false);modal('successModal',true);cart=[];saveLocal();updateCart();renderMenu();document.getElementById('note').value='';try{tg&&tg.HapticFeedback&&tg.HapticFeedback.notificationOccurred('success');}catch(_){}}catch(error){console.error(error);toast(error.message||'Buyurtma yuborilmadi');}finally{submitting=false;button.disabled=false;button.textContent='Buyurtma berish';}}
  function bind(){document.getElementById('searchInput').addEventListener('input',renderMenu);document.getElementById('menu').addEventListener('click',function(event){const add=event.target.closest('[data-add]');const fav=event.target.closest('[data-favorite]');if(add){addToCart(Number(add.getAttribute('data-add')));return;}if(fav){const id=Number(fav.getAttribute('data-favorite'));favorites=favorites.includes(id)?favorites.filter(function(x){return x!==id;}):favorites.concat(id);saveLocal();renderMenu();haptic('light');}});document.getElementById('cartItems').addEventListener('click',function(event){const button=event.target.closest('[data-change]');if(button)changeQty(Number(button.getAttribute('data-change')),Number(button.getAttribute('data-delta')));});document.getElementById('cartButton').onclick=function(){modal('cartModal',true);};document.getElementById('closeCart').onclick=function(){modal('cartModal',false);};document.getElementById('doneButton').onclick=function(){modal('successModal',false);};document.querySelectorAll('.modal').forEach(function(x){x.addEventListener('click',function(e){if(e.target===x)modal(x.id,false);});});}
  async function start(){loadLocal();bind();updateCart();window.addEventListener('online',function(){document.body.classList.remove('is-offline');});window.addEventListener('offline',function(){document.body.classList.add('is-offline');});if(!navigator.onLine)document.body.classList.add('is-offline');try{await Promise.all([loadShop(),loadMenu()]);}catch(error){document.getElementById('shopName').textContent='Menyu yuklanmadi';document.getElementById('shopLocation').textContent=error.message||'Internetni tekshiring';document.getElementById('menu').innerHTML='<div class="empty"><div class="empty-icon">⚠️</div><strong>Menyu vaqtincha ochilmadi</strong><span>Internetni tekshirib, qayta urinib ko‘ring.</span></div>';}}
  window.BozorFoodApp={getShopCode:function(){return shopCode;},reload:function(){return Promise.all([loadShop(),loadMenu()]);}};start();
})();
